# Akati OS Center: every text in English and Thai. Dot-sourced by AkatiCenter.ps1; T 'key' reads it.
# Both languages must have the same keys (tools/test-center.ps1 checks it in CI).
$strings = @{
    en = @{
        'admin' = 'Administrator mode'; 'menu' = 'MENU'
        'nav.dashboard' = 'Dashboard'; 'nav.gaming' = 'Gaming apps'; 'nav.tweaks' = 'Tweaks'
        'nav.cleaner' = 'Cleaner'; 'nav.appearance' = 'Appearance'; 'nav.about' = 'About'
        'welcome' = 'Welcome back'; 'version' = 'AKATI OS VERSION'
        'cpu' = 'CPU USAGE'; 'ram' = 'RAM USAGE'; 'gpu' = 'GPU USAGE'
        'quick' = 'Quick actions'
        'greet.morning' = 'Good morning'; 'greet.afternoon' = 'Good afternoon'; 'greet.evening' = 'Good evening'; 'greet.night' = 'Good night'
        'update.checking' = 'Checking for updates...'
        'chip.boost.on' = 'Game boost on'; 'chip.boost.off' = 'Game boost off'; 'chip.power' = 'Power: {0}'; 'chip.days' = '{0}d {1}h'; 'chip.hours' = '{0}h {1}m'
        'chip.defender.on' = 'Defender on'; 'chip.defender.off' = 'Defender off'; 'chip.uptime' = 'Up {0}'
        'disk.title' = 'Storage'; 'disk.free' = '{0} free of {1}'; 'disk.local' = 'Local Disk'
        'net.title' = 'Network'; 'net.down' = 'DOWNLOAD'; 'net.up' = 'UPLOAD'; 'net.ping' = 'PING (SG)'
        'top.title' = 'Busiest apps'; 'top.ram' = 'Memory'; 'top.self' = 'Akati OS Center'; 'disk.clean' = 'Free up space'; 'top.end' = 'Quit'; 'top.confirm' = 'Quit {0}? Unsaved work in it is lost.'
        'status.ended' = '{0} was closed'
        'quick.boost' = 'Game boost'; 'quick.boost.d' = 'Start or stop it here'
        'quick.clean' = 'Clean temp files'; 'quick.clean.d' = 'Free up disk space'
        'quick.update' = 'Check for updates'; 'quick.update.d' = 'Compare with GitHub'
        'quick.system' = 'Tweaks'; 'quick.system.d' = 'Gaming and Windows settings'
        'tweaks.gaming' = 'Gaming'; 'tweaks.system' = 'System'
        'nav.system' = 'System settings'; 'system.title' = 'System settings'
        'system.sub' = 'All Windows settings of Akati OS. A button applies that option; scripts open in a window that explains what they change. The default badge marks the Akati OS default.'
        'system.search' = 'Search settings'; 'system.links' = 'Links and tools'
        'system.cat.Software' = 'Software'; 'system.cat.Drivers' = 'Drivers'; 'system.cat.General Configuration' = 'General'
        'system.cat.Interface Tweaks' = 'Interface'; 'system.cat.Windows Settings' = 'Windows Settings'
        'system.cat.Advanced Configuration' = 'Advanced'; 'system.cat.Security' = 'Security'
        'system.cat.Additional Tools' = 'Additional tools'; 'system.cat.Troubleshooting' = 'Troubleshooting'; 'system.cat.AkatiOS' = 'Akati OS'
        'status.applied' = 'Applied: {0}'; 'status.opened' = 'Opened: {0}'
        'gaming.title' = 'Gaming apps'
        'gaming.sub' = 'Akati OS does not install apps during setup. Install them here, from official sources (WinGet, or the official installer for Steam, Discord and Riot).'
        'gpu.title' = 'GPU drivers'; 'gpu.sub' = 'Opens the official driver download page.'
        'tweaks.title' = 'Tweaks'
        'tweaks.sub' = 'Gaming switches show the current state of your PC; turn one off again if games run worse. Below are all Windows settings.'
        'cleaner.title' = 'Cleaner'; 'cleaner.sub' = 'Deletes temporary files. Files that are in use are skipped.'
        'cleaner.total' = 'SELECTED'; 'cleaner.scan' = 'Scan'; 'cleaner.clean' = 'Clean now'
        'appearance.title' = 'Appearance'; 'appearance.sub' = 'Pick an Akati OS theme. Windows applies it right away.'
        'links' = 'Links'; 'link.options' = 'Options guide'; 'credits' = 'Credits'
        'credits.text' = 'Akati OS is based on AtlasOS by the Atlas team and is licensed under GPL-3.0. It is not an official AtlasOS project. AME Wizard by Ameliorated.'
        'ready' = 'Ready'
        'installed' = 'Installed'; 'notinstalled' = 'Not installed'; 'install' = 'Install'; 'installing' = 'Installing...'
        'apply' = 'Apply'; 'active' = 'Active'
        'restart' = 'Restart to apply'
        'status.installing' = 'Installing {0}...'; 'status.installed' = '{0} installed'; 'status.notinstalled' = '{0} was not installed. Get it from its official website.'
        'status.tweak' = 'Applying: {0}...'; 'status.tweakdone' = '{0}: done'
        'status.scanning' = 'Scanning...'; 'status.cleaning' = 'Cleaning...'; 'status.cleaned' = 'Freed {0}'
        'status.theme' = 'Theme applied: {0}'
        'status.checking' = 'Checking for updates...'
        'update.latest' = 'You have the latest version ({0}).'
        'update.ahead' = 'Test build · latest release {0}'
        'update.new' = 'New version available: {0}. A new version needs a fresh Windows install.'
        'update.error' = 'Could not reach GitHub.'
        'update.open' = 'Open release page'
        'clean.temp' = 'Temporary files (your account)'; 'clean.wintemp' = 'Windows temporary files'
        'clean.dumps' = 'Crash dumps and error reports'; 'clean.recycle' = 'Recycle Bin'
        'clean.update' = 'Windows Update downloads'; 'clean.logs' = 'Windows setup logs'; 'clean.thumbs' = 'Thumbnail cache'
        'clean.apps' = 'Discord, Steam and Epic caches'; 'clean.browser' = 'Browser caches'; 'clean.shaders' = 'GPU shader caches'
        'clean.temp.d' = 'Files apps leave in your Temp folder'; 'clean.wintemp.d' = 'C:\Windows\Temp'
        'clean.update.d' = 'Update files that are already installed (Windows downloads them again if needed)'
        'clean.dumps.d' = 'Crash dumps and Windows Error Reporting files'; 'clean.logs.d' = 'CBS, DISM and setup logs'
        'clean.thumbs.d' = 'Picture previews in File Explorer, made again when needed'
        'clean.apps.d' = 'Web caches only; your logins and settings stay'
        'clean.browser.d' = 'Brave, Edge, Chrome and Firefox. No cookies or passwords. Pages load slower once'
        'clean.shaders.d' = 'NVIDIA, AMD, Intel and DirectX. Games stutter once while they build them again'
        'clean.recycle.d' = 'Deleted files in the Recycle Bin'
        'tw.hags' = 'Hardware-accelerated GPU scheduling'; 'tw.hags.d' = 'Lets the GPU manage its own memory. Needs a supported GPU and driver.'
        'tw.windowed' = 'Optimizations for windowed games'; 'tw.windowed.d' = 'Lower latency for DirectX 10/11 games in windowed and borderless mode.'
        'tw.gamemode' = 'Game Mode'; 'tw.gamemode.d' = 'Windows gives games priority and pauses some background work while you play.'
        'tw.maxperf' = 'Maximum Performance power plan'; 'tw.maxperf.d' = 'Akati OS Power Scheme with power saving off. Best for desktops, uses more battery on laptops.'
        'tw.hibernation' = 'Hibernation'; 'tw.hibernation.d' = 'Off saves disk space. Shut down and restart work normally.'
        'tw.store' = 'Microsoft Store'; 'tw.store.d' = 'Needed by the Xbox app and Game Pass. Installing it again can take a minute.'
        'tw.group.latency' = 'Input and latency'; 'tw.group.network' = 'Network'; 'tw.group.graphics' = 'Display and graphics'; 'tw.group.system' = 'Memory and system'; 'tw.group.services' = 'Services'
        'tw.timer' = 'Timer resolution 0.5 ms'; 'tw.timer.d' = 'Windows wakes up more often, so games keep a steadier frame time and lower input delay. Uses a little more power. Recommended: on.'
        'tw.access' = 'Sticky Keys and Filter Keys shortcuts'; 'tw.access.d' = 'Off: pressing Shift 5 times or holding Shift in a game no longer opens a window. The accessibility features still work from Settings. Takes effect after you sign in again.'
        'tw.dns' = 'DNS server'; 'tw.dns.d' = 'Which server turns names into addresses. Cloudflare and Google are often faster than your provider. Does not change ping inside games.'
        'dns.auto' = 'Automatic'; 'dns.cloudflare' = 'Cloudflare'; 'dns.google' = 'Google'; 'status.dns' = 'DNS: {0}'
        'tw.nagle' = "Nagle's algorithm"; 'tw.nagle.d' = 'Windows waits a moment to send small packets together. Off can lower delay in some older online games (for example World of Warcraft); most games already turn it off themselves.'
        'tw.nic' = 'Network adapter power saving and interrupt moderation'; 'tw.nic.d' = 'Off: the network card answers every packet at once and does not save power. Slightly lower delay, a little more CPU use. The connection drops for a few seconds when changed.'
        'tw.refresh' = 'Screen refresh rate'; 'tw.refresh.now' = '{0} Hz now. This screen can do {1} Hz: games look smoother and react faster at the highest rate.'
        'tw.refresh.max' = '{0} Hz, the highest this screen can do.'; 'tw.refresh.use' = 'Use {0} Hz'; 'status.refresh' = 'Screen set to {0} Hz'; 'status.refreshfail' = 'Could not change the refresh rate ({0})'
        'tw.mpo' = 'Multiplane overlay (MPO)'; 'tw.mpo.d' = 'Off fixes flickering, black screens and stutter on some PCs (often NVIDIA with two screens). Leave it on if you have no problems.'
        'tw.msi' = 'GPU message signaled interrupts (MSI mode)'; 'tw.msi.d' = 'The graphics card talks to the CPU with MSI instead of shared interrupt lines: lower latency. Most new cards already use it. Recommended: on.'
        'tw.memcomp' = 'Memory compression'; 'tw.memcomp.d' = 'Windows compresses memory instead of writing it to disk. Saves RAM, costs a little CPU.'
        'tw.memcomp.off' = 'Recommended for this PC ({0} GB RAM): off.'; 'tw.memcomp.on' = 'Recommended for this PC ({0} GB RAM): on.'; 'tw.memcomp.nosysmain' = 'Needs SysMain (SuperFetch): turn it on in System below first.'
        'tw.extrasvc' = 'Turn off more unused services'; 'tw.extrasvc.d' = 'Maps, Phone, Smart card, Payments and NFC, Wallet, Parental controls, Retail demo, Windows Insider, AllJoyn, Fax, Media sharing, Recommended troubleshooting, Remote Desktop, WinRM, Hyper-V guest services and Edge updates. Turn it off again if you need one of them.'
        'tw.svcxbox' = 'Turn off Xbox services'; 'tw.svcxbox.d' = 'Xbox app sign-in, Game Pass, Xbox cloud saves and Xbox controller accessories. Valorant and FiveM do not use them.'
        'tw.svciphelper' = 'Turn off IP Helper'; 'tw.svciphelper.d' = 'IPv6 tunnels (Teredo) that Xbox Live party chat and some games use for connections.'
        'tw.svchello' = 'Turn off Windows Hello biometrics'; 'tw.svchello.d' = 'Fingerprint and face sign-in stop working. PIN and password still work.'
        'tw.svcscanner' = 'Turn off scanners and cameras (WIA)'; 'tw.svcscanner.d' = 'Scanners and some older webcams. Most USB webcams do not need it.'
        'tw.svchotspot' = 'Turn off Mobile hotspot'; 'tw.svchotspot.d' = 'Sharing this PC''s internet with other devices.'
        'tw.svcnotify' = 'Turn off the notification service'; 'tw.svcnotify.d' = 'All app notifications and the notification center. Some apps may behave oddly; turn it back on if they do.'
        'tw.svccdp' = 'Turn off Connected Devices'; 'tw.svccdp.d' = 'Phone Link, Nearby sharing and sharing between your devices.'
        'ac.title' = 'Anti-cheat mode'; 'ac.sub' = 'Valorant (Vanguard) can ask for Memory integrity on, FiveM needs it off. Pick the game you play next; Windows changes it after a restart.'
        'ac.valorant' = 'Valorant mode'; 'ac.fivem' = 'FiveM mode'; 'ac.on' = 'Memory integrity: on (Valorant mode)'; 'ac.off' = 'Memory integrity: off (FiveM mode)'; 'ac.pending' = 'restart to apply'
        'ac.restartask' = 'Windows changes Memory integrity when it starts. Restart now?'
        'restart.bar' = 'Restart to finish the changes'; 'restart.now' = 'Restart now'; 'restart.ask' = 'Restart the PC now? Save your work first.'
        'toast.on' = 'On: {0}'; 'toast.off' = 'Off: {0}'; 'toast.undo' = 'Undo'; 'tw.details' = 'What it changes'; 'spot.recent' = 'Recent'
        'side.narrow' = 'Narrow sidebar'; 'side.wide' = 'Wide sidebar'
        'preset.title' = 'Style presets'; 'preset.sub' = 'Wallpaper, accent color, Akati OS Center look, cursor and sounds in one click.'
        'preset.neon' = 'Neon'; 'preset.ocean' = 'Ocean'; 'preset.ember' = 'Ember'; 'preset.sakura' = 'Sakura'; 'preset.stealth' = 'Stealth (OLED)'
        'status.preset' = 'Style {0} applied'; 'accent.wallpaper' = 'From the wallpaper'; 'accent.nowallcolor' = 'The wallpaper has no color to take (black, white or gray)'
        'tw.group.looks' = 'Windows look'
        'tw.darkmode' = 'Dark mode'; 'tw.darkmode.d' = 'Windows and apps use dark colors.'
        'tw.accentbars' = 'Accent color on title bars and taskbar'; 'tw.accentbars.d' = 'Title bars, Start and the taskbar use the accent color of Appearance.'
        'tw.transparency' = 'Transparency effects'; 'tw.transparency.d' = 'See-through Start, taskbar and windows. Off saves a little GPU work.'
        'tw.widget' = 'Performance widget'; 'tw.widget.d' = 'A small bar on top of other windows with CPU, RAM, GPU, GPU temperature and ping. Drag to move, right-click to close. Also in the menu of the icon next to the clock.'
        'chip.doctor.ok' = 'Health: all good'; 'chip.doctor.bad' = 'Health: {0} to check'
        'nav.health' = 'Health'; 'doc.title' = 'Akati Doctor'; 'doc.run' = 'Check again'; 'doc.checking' = 'Checking your PC...'
        'doc.allgood' = 'Everything looks good'; 'doc.issues' = '{0} things to look at'; 'doc.checked' = 'checked at {0}'
        'doc.failed' = 'The check did not finish'; 'doc.fixing' = 'Fixing...'
        'doc.tray.ok' = 'The icon next to the clock is set up'; 'doc.tray.bad' = 'The icon next to the clock is not set up'; 'doc.fix.tray' = 'Set up'
        'doc.menu.ok' = 'The desktop menu works'; 'doc.menu.bad' = 'The task of the desktop menu is missing'; 'doc.fix.menu' = 'Repair'
        'doc.power.ok' = 'A power plan for performance is active'; 'doc.power.bad' = 'A balanced or power saving plan is active'; 'doc.fix.power' = 'Use best performance'
        'doc.disk.ok' = '{0}% of the Windows drive is free'; 'doc.disk.bad' = 'Only {0}% of the Windows drive is free'; 'doc.fix.disk' = 'Clean'
        'doc.restart.ok' = 'No restart is waiting'; 'doc.restart.bad' = 'Windows waits for a restart to finish updates'; 'doc.fix.restart' = 'Restart'
        'doc.hvci.ok' = 'Memory integrity runs as set'; 'doc.hvci.bad' = 'Memory integrity changes after a restart'; 'doc.fix.hvci' = 'Restart'
        'doc.devices.ok' = 'All devices work'; 'doc.devices.bad' = '{0} devices have a problem (driver missing or not working)'; 'doc.fix.devices' = 'Device Manager'
        'doc.crash.ok' = 'No blue screens in the last 7 days'; 'doc.crash.bad' = '{0} blue screens in the last 7 days'; 'doc.fix.crash' = 'Show'
        'doc.repair' = 'Repair Windows files'; 'doc.repair.d' = 'Runs DISM and SFC in a window. Takes 10 to 30 minutes and needs the internet.'; 'doc.repair.button' = 'Repair'
        'health.speed' = 'Startup and temperatures'; 'boot.last' = 'Windows started in {0:N1} s'
        'boot.avg' = 'Last start. Average of the last {0} starts: {1:N1} s'
        'boot.none' = 'Windows has not recorded a start time yet (the Diagnostics-Performance log is off or empty).'
        'boot.off' = 'This Windows does not record how long it takes to start (the Diagnostics-Performance log is off).'
        'boot.enable' = 'Record the startup time'; 'boot.next' = 'Recording is on. The time shows here after the next restart.'; 'boot.failed' = 'Windows did not turn the log on'
        'temp.now' = 'Temperatures now: {0}'; 'temp.none' = 'Windows reports no temperatures on this PC. HWiNFO shows every sensor.'
        'chip.temp.sys' = 'System {0}°C'; 'chip.temp.gpu' = 'GPU {0}°C'
        'crash.title' = 'Crashes in the last 30 days'; 'crash.none' = 'No crashes. Nice.'; 'crash.bsod' = 'Blue screen {0}'
        'crash.power' = 'The PC turned off without shutting down'; 'crash.app' = '{0} stopped working'; 'crash.folder' = 'Crash dump folder'
        'wu.title' = 'Windows Update'; 'wu.sub' = 'Pause updates before a tournament or a long gaming night. Updates come again when the pause ends.'
        'wu.on' = 'Updates are on'; 'wu.paused' = 'Updates are paused until {0}'; 'wu.pause7' = 'Pause 1 week'; 'wu.pause35' = 'Pause 5 weeks'
        'wu.resume' = 'Resume updates'; 'wu.open' = 'Open Windows Update'
        'history.title' = 'Change history'; 'history.none' = 'Switches you change in Tweaks show here, with Undo.'; 'history.clear' = 'Clear'
        'history.on' = 'Turned on'; 'history.off' = 'Turned off'
        'backup.title' = 'Backup'; 'backup.sub' = 'Save your Akati OS Center settings, My games with their profiles and every switch to a file, and restore them after a new install.'
        'backup.save' = 'Save backup'; 'backup.load' = 'Restore'; 'backup.saved' = 'Backup saved: {0}'
        'backup.ask' = 'Restore the settings from this backup? Switches that differ are changed now.'
        'backup.restored' = 'Restored. {0} switches changed. Some settings show after Akati OS Center opens again.'; 'backup.bad' = 'This file is not an Akati OS backup'
        'tw.mouseaccel' = 'Mouse acceleration'; 'tw.mouseaccel.d' = 'Enhance pointer precision in Windows. Off: the pointer moves the same distance however fast you move the mouse, best for aiming.'
        'tw.ducking' = 'Lower other sounds during calls'; 'tw.ducking.d' = 'Windows turns game sound down by 80% when it sees a call (Discord can start it). Off keeps the game at full volume.'
        'tw.keydelay' = 'Short key repeat delay'; 'tw.keydelay.d' = 'A held key repeats sooner. After the next sign-in.'
        'games.boost' = 'Boost'; 'games.boost.tip' = 'Play starts Game boost first'; 'games.core0' = 'Skip CPU 0'
        'games.core0.tip' = 'The game runs on every core but CPU 0, where Windows handles most interrupts. Set by the icon next to the clock when the game starts.'
        'games.hvci.any' = 'Memory integrity: any'; 'games.hvci.on' = 'Needs Memory integrity on'; 'games.hvci.off' = 'Needs Memory integrity off'
        'games.hvci.tip' = 'Valorant can need it on, FiveM needs it off. Play offers to switch it.'; 'games.play' = 'Play'; 'games.on' = 'on'; 'games.off' = 'off'
        'games.hvciask' = '{0} needs Memory integrity {1}. Switch it now? Windows changes it after a restart. No starts the game as it is.'; 'status.gamestarted' = 'Started {0}'
        'fivem.title' = 'FiveM'; 'fivem.sub' = 'Clean the cache when servers load slowly or textures break, and check the connection time to your server.'
        'fivem.found' = 'FiveM found: {0}'; 'fivem.none' = 'FiveM is not installed for this user.'; 'fivem.clear' = 'Clear cache'; 'fivem.open' = 'Open folder'; 'fivem.add' = 'Add to My games'
        'fivem.server' = 'Server IP:port, for example 1.2.3.4:30120'; 'fivem.ping' = 'Test'; 'fivem.running' = 'Close FiveM first.'; 'fivem.cleared' = 'FiveM cache cleared: {0}'
        'fivem.result' = 'Connection time to {0}: {1} ms'; 'fivem.fail' = 'Could not connect to {0}'; 'fivem.added' = 'FiveM is in My games'
        'boost.sound' = 'Sound and effect when Game boost starts'
        'tw.hotkeys' = 'Shortcut keys'; 'tw.hotkeys.d' = 'Ctrl+Alt+B starts or stops Game boost and Ctrl+Alt+R frees up RAM, also inside games. Needs the icon next to the clock.'
        'tw.vbs' = 'Core isolation (VBS and Memory integrity)'; 'tw.vbs.d' = 'Off can make games up to about 10% faster, but some protection against malware is gone. Some anti-cheat (Valorant, FACEIT) may need it on (same values as the VBS scripts in System below).'
        'tw.desktopmenu' = 'Akati OS on the desktop right-click menu'; 'tw.desktopmenu.d' = 'Right-click the desktop > Akati OS: free up RAM, your apps, Game boost, cleaner, ping test, flush DNS, restart Explorer, restart into BIOS.'
        'tw.startdelay' = 'Delay for startup apps'; 'tw.startdelay.d' = 'Off: apps that start at sign-in open right away instead of a few seconds later.'
        'chip.hz' = 'Screen {0} Hz'; 'chip.hzlow' = 'Screen {0} Hz · can do {1} Hz'
        'games.title' = 'My games'; 'games.add' = 'Add game'; 'games.empty' = 'No games added yet. Add the .exe file of a game.'
        'games.sub' = 'High priority: the game gets the CPU before other apps. Dedicated GPU: laptops with two graphics chips use the fast one. Skip Defender: Defender does not scan the game folder (faster loading, less protection). Removing a game puts everything back.'
        'games.cpu' = 'High priority'; 'games.gpu' = 'Dedicated GPU'; 'games.defender' = 'Skip Defender'; 'games.remove' = 'Remove'; 'games.nodefender' = 'Defender is off or not available'
        'games.pick' = 'Choose the game (.exe)'; 'status.gameadded' = '{0} added'; 'status.gameremoved' = '{0} removed, its settings are back'
        'look.title' = 'Akati OS Center look'; 'look.sub' = 'Auto follows the Windows app mode (Settings > Personalization > Colors).'; 'look.auto' = 'Auto'; 'look.dark' = 'Dark'; 'look.light' = 'Light'
        'spot.search' = 'Search'; 'spot.hint' = 'Search pages, settings, apps and actions'; 'spot.none' = 'Nothing found'
        'spot.page' = 'Page'; 'spot.setting' = 'Setting'; 'spot.app' = 'App'; 'spot.action' = 'Action'; 'spot.game' = 'Game'; 'spot.atlas' = 'Search "{0}" in the Windows settings'
        'act.freeram' = 'Free up RAM'; 'act.flushdns' = 'Flush DNS cache'; 'act.explorer' = 'Restart Explorer'; 'act.boost' = 'Start or stop Game boost'
        'act.update' = 'Check for Akati OS updates'; 'act.lang' = 'Switch language (English / ภาษาไทย)'; 'act.ping' = 'Ping test'; 'act.report' = 'Create problem report'
        'status.freed' = 'Freed {0} of RAM'; 'status.dnsflushed' = 'DNS cache cleared'
        'new.title' = "What's new in Akati OS {0}"; 'new.done' = 'Continue'
        'new.1' = 'Dashboard: live graphs, the busiest apps, network speed and ping, drives, and the screen refresh rate'
        'new.2' = 'Gaming apps look like the App Store, with Riot Client, GOG GALAXY, Rockstar Games Launcher and MSI Afterburner'
        'new.3' = 'Tweaks: new sections for input and latency, network (DNS), display (refresh rate) and memory, and a reset to Windows defaults'
        'new.4' = 'Game boost frees up memory, has My games (priority, graphics card) and can start by itself when a game opens'
        'new.5' = 'Right-click the desktop or the Akati OS icon next to the clock: free up RAM, your apps, Game boost and more'
        'new.6' = 'Search everything with Ctrl+K, and a light look (Appearance > Akati OS Center look)'
        'boost.auto' = 'Start by itself when a game from My games opens, stop when it closes'
        'tweaks.reset' = 'Reset to Windows defaults'; 'tweaks.resetask' = 'Set Game Mode, timer resolution, Sticky Keys shortcuts, Nagle, network adapter, MPO, memory compression, startup delay and DNS back to the Windows defaults?'
        'status.reset' = 'Tweaks are back to the Windows defaults · restart to finish'
        'tw.tray' = 'Akati OS icon next to the clock'; 'tw.tray.d' = 'CPU and RAM when you point at it, a menu with your apps and tools, and the automatic Game boost. Starts when you sign in.'
        'theme.dark' = 'Akati OS Dark'; 'theme.light' = 'Akati OS Light'; 'theme.slideshow' = 'Akati OS Slideshow'
        'theme.slideshow.d' = 'Wallpaper changes every 30 minutes'
        'nav.boost' = 'Game boost'
        'cancel' = 'Cancel'; 'cancelling' = 'Cancelling...'; 'queued' = 'Waiting in the queue'; 'preparing' = 'Starting...'
        'update' = 'Update'; 'updating' = 'Updating...'; 'updateavailable' = 'Update available'; 'selfupdate' = 'updates itself'
        'apps.check' = 'Check for updates'; 'apps.updateall' = 'Update all'; 'apps.updatecount' = 'Update all ({0})'
        'apps.hint' = 'Get several apps: they install one after another.'; 'apps.starter' = 'Get Steam and Discord'
        'apps.cat.installed' = 'Installed'; 'src.winget' = 'WinGet'; 'src.official' = 'Official site'
        'apps.cat.launchers' = 'Game launchers'; 'apps.cat.social' = 'Chat and streaming'; 'apps.cat.tools' = 'Tools'
        'get' = 'Get'; 'open' = 'Open'; 'more' = 'More'; 'openfolder' = 'Open folder'; 'uninstall' = 'Uninstall'
        'uninstall.confirm' = 'Uninstall {0}? Its own uninstaller opens.'; 'uninstalling' = 'Uninstalling, finish in its window...'
        'status.opening' = 'Opening {0}'; 'status.uninstalled' = '{0} uninstalled'; 'status.nouninstaller' = 'No uninstaller found for {0}. Opening Apps and features.'
        'app.desc.Steam' = 'The biggest PC game store and your Steam library'; 'app.desc.Epic' = 'Fortnite, Epic exclusives and free games every week'
        'app.desc.EA' = 'EA SPORTS FC, Apex Legends, Battlefield and EA Play'; 'app.desc.Ubisoft' = "Assassin's Creed, Rainbow Six Siege and Ubisoft+"
        'app.desc.BattleNet' = 'Overwatch 2, Diablo, World of Warcraft and Call of Duty'; 'app.desc.Riot' = 'Installs VALORANT (Asia Pacific). Add League of Legends and TFT in Riot Client'
        'app.desc.GOG' = 'DRM-free games, and one library for all your stores'; 'app.desc.Rockstar' = 'GTA V, Red Dead Redemption 2 and Rockstar games'
        'app.desc.Discord' = 'Voice, video and text chat with friends'; 'app.desc.OBS' = 'Record and stream your games'
        'app.desc.Afterburner' = 'FPS, temperatures and GPU usage on screen while you play, and GPU tuning'
        'gpu.driver' = '{0}: driver {1} from {2}'; 'gpu.old' = 'More than 6 months old, check for a newer driver.'
        'stage.winget' = 'Installing with WinGet...'; 'stage.download' = 'Downloading'; 'stage.install' = 'Installing...'
        'stage.user' = 'Installing for your account...'; 'stage.finish' = 'Finishing...'
        'stage.window' = 'Click Install in its window to finish...'
        'status.cancelled' = '{0}: cancelled'; 'status.updating' = 'Updating {0}...'; 'status.updated' = '{0} updated'
        'status.updatefailed' = '{0} could not be updated'; 'status.checkingapps' = 'Checking WinGet for app updates...'
        'status.updatesfound' = '{0} update(s) available'; 'status.noupdates' = 'All apps are up to date'
        'status.nowinget' = 'WinGet is not installed'
        'gpu.detected' = 'Found in this PC: {0}'; 'gpu.none' = 'No NVIDIA, AMD or Intel graphics card found (virtual machine?).'
        'boost.title' = 'Game boost'
        'boost.sub' = 'One click before you play. Stop puts everything back the way it was, also after a restart.'
        'boost.mode' = 'Game Mode'; 'boost.off' = 'Off'; 'boost.on' = 'On since {0}'; 'boost.start' = 'Start'; 'boost.stop' = 'Stop'
        'boost.power' = 'Switch to the highest performance power plan'
        'boost.apps' = 'Close background apps'; 'boost.noapps' = 'none running now'
        'boost.notify' = 'Turn off notifications'
        'boost.memory' = 'Free up standby memory (files Windows keeps in RAM; helps on PCs with little RAM)'
        'status.booston' = 'Game boost is on. Have fun!'; 'status.boostoff' = 'Game boost is off, your settings are back'
        'ping.title' = 'Ping to game servers'
        'ping.sub' = 'Connection time to the cloud data centers where many games run their Asian servers. Lower is better: under 60 ms is great.'
        'ping.start' = 'Start test'; 'ping.stop' = 'Stop'; 'ping.timeout' = 'no reply'
        'ping.bkk' = 'Thailand (Bangkok)'; 'ping.sin' = 'Singapore'; 'ping.hkg' = 'Hong Kong'; 'ping.tyo' = 'Japan (Tokyo)'
        'startup.title' = 'Startup apps'
        'startup.sub' = 'Apps that start when you sign in. Fewer apps means a faster start and more free RAM for games.'
        'startup.empty' = 'No startup apps.'
        'status.startupon' = '{0} starts with Windows'; 'status.startupoff' = '{0} no longer starts with Windows'
        'system.default' = 'default'
        'restore.title' = 'Create a restore point first'; 'restore.open' = 'System Restore'
        'restore.sub' = 'Once, before the first change you make here. Needs System Restore to be on.'
        'status.restoring' = 'Creating a restore point...'
        'status.restore.made' = 'Restore point created'
        'status.restore.recent' = 'No new restore point: Windows made one less than 24 hours ago'
        'status.restore.off' = 'No restore point: System Restore is off. Turn it on with the System Restore button (Configure > Turn on system protection).'
        'status.boostpartial' = 'Game boost is on, but these steps failed: {0}'
        'status.sound.play' = 'Playing: {0}'
        'report.title' = 'Report a problem'
        'report.sub' = 'Saves one .zip on your desktop with the Akati OS logs and PC details. No personal files; your user name and PC name are removed. Attach it to a GitHub issue.'
        'report.button' = 'Create problem report'; 'report.issues' = 'GitHub issues'
        'status.report' = 'Creating the problem report...'; 'status.reportdone' = 'Saved on your desktop: {0}'; 'status.reportfailed' = 'Could not create the report'
        'accent.title' = 'Accent color'
        'accent.sub' = 'Used by Akati OS Center, the Windows accent color (highlights, buttons and links; Start and taskbar only when "Show accent color" is on in Settings) and the Akati OS Terminal colors.'
        'accent.purple' = 'Purple'; 'accent.blue' = 'Blue'; 'accent.cyan' = 'Cyan'; 'accent.green' = 'Green'
        'accent.pink' = 'Pink'; 'accent.red' = 'Red'; 'accent.orange' = 'Orange'
        'status.accent' = 'Accent color: {0}. Some parts of Windows change after you sign in again.'
        'wall.title' = 'Wallpapers'; 'wall.sub' = 'Click a picture to use it as your desktop background.'
        'status.wallpaper' = 'Wallpaper: {0}'
        'style.title' = 'Cursor and sounds'
        'style.sub' = 'The Akati OS pointer and system sounds. You can go back to the Windows ones at any time.'
        'style.cursor' = 'Cursor'; 'style.sounds' = 'Sounds'; 'style.akati' = 'Akati OS'; 'style.windows' = 'Windows'
        'style.nosound' = 'No sounds'; 'style.preview' = 'Play'
        'status.cursor.akati' = 'Akati OS cursor is on'; 'status.cursor.windows' = 'Windows cursor is back'
        'status.sound.akati' = 'Akati OS sounds are on'; 'status.sound.windows' = 'Windows sounds are on'; 'status.sound.none' = 'Sounds are off'
        'welcome.title' = 'Welcome to Akati OS'; 'welcome.sub' = 'Three quick steps. You can change everything later.'
        'welcome.lang' = 'Language'; 'welcome.apps' = 'Install your gaming apps'; 'welcome.apps.d' = 'Steam, Discord, Epic and more'
        'welcome.look' = 'Pick a theme and accent color'; 'welcome.look.d' = 'Dark, light, slideshow and 7 colors'
        'welcome.open' = 'Open'; 'welcome.done' = 'Get started'
        'welcome.keys' = 'Tip: Ctrl+1 to Ctrl+8 switch pages, Ctrl+F searches the settings.'
        'lang' = 'ภาษาไทย'
    }
    th = @{
        'admin' = 'โหมดผู้ดูแลระบบ'; 'menu' = 'เมนู'
        'nav.dashboard' = 'แดชบอร์ด'; 'nav.gaming' = 'แอปเกม'; 'nav.tweaks' = 'ปรับแต่ง'
        'nav.cleaner' = 'ล้างไฟล์ขยะ'; 'nav.appearance' = 'ธีม'; 'nav.about' = 'เกี่ยวกับ'
        'welcome' = 'ยินดีต้อนรับ'; 'version' = 'เวอร์ชัน AKATI OS'
        'cpu' = 'การใช้ CPU'; 'ram' = 'การใช้ RAM'; 'gpu' = 'การใช้ GPU'
        'quick' = 'ทางลัด'
        'greet.morning' = 'สวัสดีตอนเช้า'; 'greet.afternoon' = 'สวัสดีตอนบ่าย'; 'greet.evening' = 'สวัสดีตอนเย็น'; 'greet.night' = 'สวัสดีตอนค่ำ'
        'update.checking' = 'กำลังตรวจอัปเดต...'
        'chip.boost.on' = 'บูสต์เกมเปิดอยู่'; 'chip.boost.off' = 'บูสต์เกมปิดอยู่'; 'chip.power' = 'แผนพลังงาน: {0}'; 'chip.days' = '{0} วัน {1} ชม.'; 'chip.hours' = '{0} ชม. {1} นาที'
        'chip.defender.on' = 'Defender เปิดอยู่'; 'chip.defender.off' = 'Defender ปิดอยู่'; 'chip.uptime' = 'เปิดเครื่องมา {0}'
        'disk.title' = 'พื้นที่เก็บข้อมูล'; 'disk.free' = 'ว่าง {0} จาก {1}'; 'disk.local' = 'ดิสก์ในเครื่อง'
        'net.title' = 'เครือข่าย'; 'net.down' = 'ดาวน์โหลด'; 'net.up' = 'อัปโหลด'; 'net.ping' = 'ปิง (สิงคโปร์)'
        'top.title' = 'แอปที่ใช้ทรัพยากรมากที่สุด'; 'top.ram' = 'หน่วยความจำ'; 'top.self' = 'Akati OS Center'; 'disk.clean' = 'ล้างพื้นที่'; 'top.end' = 'ปิด'; 'top.confirm' = 'ปิด {0} ใช่ไหม งานที่ยังไม่ได้บันทึกในแอปนี้จะหายไป'
        'status.ended' = 'ปิด {0} แล้ว'
        'quick.boost' = 'บูสต์เกม'; 'quick.boost.d' = 'เปิดหรือปิดได้ที่นี่'
        'quick.clean' = 'ล้างไฟล์ชั่วคราว'; 'quick.clean.d' = 'เพิ่มพื้นที่ดิสก์'
        'quick.update' = 'ตรวจอัปเดต'; 'quick.update.d' = 'เทียบกับ GitHub'
        'quick.system' = 'ปรับแต่ง'; 'quick.system.d' = 'เกมและการตั้งค่า Windows'
        'tweaks.gaming' = 'เกม'; 'tweaks.system' = 'ระบบ'
        'nav.system' = 'ตั้งค่าระบบ'; 'system.title' = 'ตั้งค่าระบบ'
        'system.sub' = 'การตั้งค่า Windows ทั้งหมดของ Akati OS กดปุ่มเพื่อใช้ตัวเลือกนั้น สคริปต์จะเปิดในหน้าต่างที่อธิบายว่าเปลี่ยนอะไร ป้าย ค่าเริ่มต้น คือค่าที่ Akati OS ใช้ หน้าต่างของสคริปต์เป็นภาษาอังกฤษ'
        'system.search' = 'ค้นหาการตั้งค่า'; 'system.links' = 'ลิงก์และเครื่องมือ'
        'system.cat.Software' = 'ซอฟต์แวร์'; 'system.cat.Drivers' = 'ไดรเวอร์'; 'system.cat.General Configuration' = 'ทั่วไป'
        'system.cat.Interface Tweaks' = 'หน้าตา'; 'system.cat.Windows Settings' = 'การตั้งค่า Windows'
        'system.cat.Advanced Configuration' = 'ขั้นสูง'; 'system.cat.Security' = 'ความปลอดภัย'
        'system.cat.Additional Tools' = 'เครื่องมือเพิ่มเติม'; 'system.cat.Troubleshooting' = 'แก้ปัญหา'; 'system.cat.AkatiOS' = 'Akati OS'
        'status.applied' = 'ใช้แล้ว: {0}'; 'status.opened' = 'เปิดแล้ว: {0}'
        'gaming.title' = 'แอปเกม'
        'gaming.sub' = 'Akati OS ไม่ได้ติดตั้งแอปให้ตอนลง กดติดตั้งได้ที่นี่ โหลดจากแหล่งทางการ (WinGet หรือตัวติดตั้งทางการของ Steam, Discord และ Riot)'
        'gpu.title' = 'ไดรเวอร์การ์ดจอ'; 'gpu.sub' = 'เปิดหน้าดาวน์โหลดไดรเวอร์ทางการ'
        'tweaks.title' = 'ปรับแต่ง'
        'tweaks.sub' = 'สวิตช์เกมแสดงสถานะจริงของเครื่อง ถ้าเปิดแล้วเกมแย่ลงให้ปิดกลับ ด้านล่างคือการตั้งค่า Windows ทั้งหมด'
        'cleaner.title' = 'ล้างไฟล์ขยะ'; 'cleaner.sub' = 'ลบไฟล์ชั่วคราว ไฟล์ที่กำลังใช้งานอยู่จะถูกข้าม'
        'cleaner.total' = 'ที่เลือกไว้'; 'cleaner.scan' = 'สแกน'; 'cleaner.clean' = 'ล้างเลย'
        'appearance.title' = 'ธีม'; 'appearance.sub' = 'เลือกธีมของ Akati OS แล้ว Windows จะเปลี่ยนให้ทันที'
        'links' = 'ลิงก์'; 'link.options' = 'คู่มือตัวเลือก'; 'credits' = 'เครดิต'
        'credits.text' = 'Akati OS ดัดแปลงจาก AtlasOS ของทีม Atlas ใช้สัญญาอนุญาต GPL-3.0 ไม่ใช่โปรเจกต์ทางการของ AtlasOS ใช้งานผ่าน AME Wizard ของ Ameliorated'
        'ready' = 'พร้อมใช้งาน'
        'installed' = 'ติดตั้งแล้ว'; 'notinstalled' = 'ยังไม่ได้ติดตั้ง'; 'install' = 'ติดตั้ง'; 'installing' = 'กำลังติดตั้ง...'
        'apply' = 'ใช้ธีมนี้'; 'active' = 'ใช้อยู่'
        'restart' = 'รีสตาร์ตเพื่อให้มีผล'
        'status.installing' = 'กำลังติดตั้ง {0}...'; 'status.installed' = 'ติดตั้ง {0} แล้ว'; 'status.notinstalled' = 'ติดตั้ง {0} ไม่สำเร็จ ให้ติดตั้งจากเว็บไซต์ทางการ'
        'status.tweak' = 'กำลังปรับ: {0}...'; 'status.tweakdone' = '{0}: เรียบร้อย'
        'status.scanning' = 'กำลังสแกน...'; 'status.cleaning' = 'กำลังล้าง...'; 'status.cleaned' = 'ล้างได้ {0}'
        'status.theme' = 'เปลี่ยนธีมเป็น {0} แล้ว'
        'status.checking' = 'กำลังตรวจอัปเดต...'
        'update.latest' = 'ใช้เวอร์ชันล่าสุดอยู่แล้ว ({0})'
        'update.ahead' = 'ตัวทดสอบ · release ล่าสุด {0}'
        'update.new' = 'มีเวอร์ชันใหม่: {0} ต้องลง Windows ใหม่พร้อมไฟล์ .apbx ตัวใหม่'
        'update.error' = 'เชื่อมต่อ GitHub ไม่ได้'
        'update.open' = 'เปิดหน้า release'
        'clean.temp' = 'ไฟล์ชั่วคราว (บัญชีของคุณ)'; 'clean.wintemp' = 'ไฟล์ชั่วคราวของ Windows'
        'clean.dumps' = 'Crash dump และรายงานข้อผิดพลาด'; 'clean.recycle' = 'ถังขยะ'
        'clean.update' = 'ไฟล์ดาวน์โหลดของ Windows Update'; 'clean.logs' = 'Log การติดตั้งของ Windows'; 'clean.thumbs' = 'แคชภาพย่อ'
        'clean.apps' = 'แคชของ Discord, Steam และ Epic'; 'clean.browser' = 'แคชเบราว์เซอร์'; 'clean.shaders' = 'แคช shader ของการ์ดจอ'
        'clean.temp.d' = 'ไฟล์ที่แอปทิ้งไว้ในโฟลเดอร์ Temp'; 'clean.wintemp.d' = 'C:\Windows\Temp'
        'clean.update.d' = 'ไฟล์อัปเดตที่ติดตั้งไปแล้ว (Windows โหลดใหม่เองถ้าต้องใช้)'
        'clean.dumps.d' = 'Crash dump และไฟล์ Windows Error Reporting'; 'clean.logs.d' = 'Log ของ CBS, DISM และการติดตั้ง'
        'clean.thumbs.d' = 'ภาพตัวอย่างใน File Explorer สร้างใหม่เองเมื่อเปิดดู'
        'clean.apps.d' = 'เฉพาะแคชเว็บ การล็อกอินและการตั้งค่ายังอยู่'
        'clean.browser.d' = 'Brave, Edge, Chrome และ Firefox ไม่ลบคุกกี้หรือรหัสผ่าน หน้าเว็บโหลดช้าลงครั้งแรก'
        'clean.shaders.d' = 'NVIDIA, AMD, Intel และ DirectX เกมจะกระตุกครั้งแรกระหว่างสร้างใหม่'
        'clean.recycle.d' = 'ไฟล์ที่ลบไว้ในถังขยะ'
        'tw.hags' = 'Hardware-accelerated GPU scheduling'; 'tw.hags.d' = 'ให้การ์ดจอจัดการหน่วยความจำเอง ต้องใช้การ์ดจอและไดรเวอร์ที่รองรับ'
        'tw.windowed' = 'Optimizations for windowed games'; 'tw.windowed.d' = 'ลด latency ของเกม DirectX 10/11 ที่เล่นแบบหน้าต่างหรือ borderless'
        'tw.gamemode' = 'Game Mode'; 'tw.gamemode.d' = 'Windows ให้ความสำคัญกับเกมและพักงานเบื้องหลังบางอย่างระหว่างเล่น'
        'tw.maxperf' = 'Power plan ประสิทธิภาพสูงสุด'; 'tw.maxperf.d' = 'Akati OS Power Scheme และปิดการประหยัดพลังงาน เหมาะกับคอมตั้งโต๊ะ โน้ตบุ๊กจะเปลืองแบต'
        'tw.hibernation' = 'Hibernation'; 'tw.hibernation.d' = 'ปิดไว้ช่วยประหยัดพื้นที่ดิสก์ ปิดเครื่องและรีสตาร์ตได้ตามปกติ'
        'tw.store' = 'Microsoft Store'; 'tw.store.d' = 'แอป Xbox และ Game Pass ต้องใช้ การติดตั้งกลับอาจใช้เวลาประมาณ 1 นาที'
        'tw.group.latency' = 'อินพุตและ latency'; 'tw.group.network' = 'เครือข่าย'; 'tw.group.graphics' = 'หน้าจอและกราฟิก'; 'tw.group.system' = 'หน่วยความจำและระบบ'; 'tw.group.services' = 'Services (บริการของ Windows)'
        'tw.timer' = 'Timer resolution 0.5 ms'; 'tw.timer.d' = 'Windows ตื่นถี่ขึ้น เฟรมเกมนิ่งขึ้นและ input delay ลดลง ใช้ไฟเพิ่มเล็กน้อย แนะนำ: เปิด'
        'tw.access' = 'ปุ่มลัด Sticky Keys และ Filter Keys'; 'tw.access.d' = 'ปิด: กด Shift 5 ครั้งหรือกด Shift ค้างในเกมจะไม่มีหน้าต่างเด้ง ฟีเจอร์ช่วยการเข้าถึงยังใช้ได้จาก Settings มีผลหลังล็อกอินใหม่'
        'tw.dns' = 'DNS server'; 'tw.dns.d' = 'เซิร์ฟเวอร์ที่แปลงชื่อเว็บเป็นที่อยู่ Cloudflare และ Google มักเร็วกว่าของผู้ให้บริการ ไม่ได้ลดปิงในเกม'
        'dns.auto' = 'อัตโนมัติ'; 'dns.cloudflare' = 'Cloudflare'; 'dns.google' = 'Google'; 'status.dns' = 'DNS: {0}'
        'tw.nagle' = "Nagle's algorithm"; 'tw.nagle.d' = 'Windows รอรวมแพ็กเก็ตเล็ก ๆ ก่อนส่ง ปิดแล้วช่วยลด delay ในเกมออนไลน์เก่าบางเกม (เช่น World of Warcraft) เกมส่วนใหญ่ปิดเองอยู่แล้ว'
        'tw.nic' = 'การประหยัดไฟและ interrupt moderation ของการ์ดแลน'; 'tw.nic.d' = 'ปิด: การ์ดแลนตอบทุกแพ็กเก็ตทันทีและไม่ประหยัดไฟ delay ลดลงเล็กน้อย ใช้ CPU เพิ่มนิดหน่อย เน็ตจะหลุดไม่กี่วินาทีตอนเปลี่ยน'
        'tw.refresh' = 'อัตรารีเฟรชหน้าจอ'; 'tw.refresh.now' = 'ตอนนี้ {0} Hz จอนี้ทำได้ถึง {1} Hz ที่ค่าสูงสุดเกมจะลื่นและตอบสนองไวขึ้น'
        'tw.refresh.max' = '{0} Hz สูงสุดของจอนี้แล้ว'; 'tw.refresh.use' = 'ใช้ {0} Hz'; 'status.refresh' = 'ตั้งจอเป็น {0} Hz แล้ว'; 'status.refreshfail' = 'เปลี่ยนอัตรารีเฟรชไม่ได้ ({0})'
        'tw.mpo' = 'Multiplane overlay (MPO)'; 'tw.mpo.d' = 'ปิดแล้วแก้จอกระพริบ จอดำ และกระตุกในบางเครื่อง (มักเป็น NVIDIA กับจอสองจอ) ถ้าไม่มีปัญหาให้เปิดไว้'
        'tw.msi' = 'MSI mode ของการ์ดจอ'; 'tw.msi.d' = 'การ์ดจอคุยกับ CPU แบบ MSI แทนสาย interrupt ที่ใช้ร่วมกัน latency ต่ำลง การ์ดใหม่ส่วนใหญ่ใช้อยู่แล้ว แนะนำ: เปิด'
        'tw.memcomp' = 'Memory compression'; 'tw.memcomp.d' = 'Windows บีบอัดหน่วยความจำแทนการเขียนลงดิสก์ ประหยัด RAM แต่ใช้ CPU เล็กน้อย'
        'tw.memcomp.off' = 'แนะนำสำหรับเครื่องนี้ (RAM {0} GB): ปิด'; 'tw.memcomp.on' = 'แนะนำสำหรับเครื่องนี้ (RAM {0} GB): เปิด'; 'tw.memcomp.nosysmain' = 'ต้องเปิด SysMain (SuperFetch) ก่อน ในหมวดระบบด้านล่าง'
        'tw.extrasvc' = 'ปิด service ที่ไม่ได้ใช้เพิ่มเติม'; 'tw.extrasvc.d' = 'แผนที่, Phone, Smart card, Payments และ NFC, Wallet, การควบคุมโดยผู้ปกครอง, Retail demo, Windows Insider, AllJoyn, Fax, การแชร์สื่อ, Recommended troubleshooting, Remote Desktop, WinRM, service ของ Hyper-V guest และตัวอัปเดต Edge ปิดสวิตช์นี้ถ้าต้องใช้ตัวใดตัวหนึ่ง'
        'tw.svcxbox' = 'ปิด Xbox services'; 'tw.svcxbox.d' = 'ล็อกอินแอป Xbox, Game Pass, เซฟเกมบนคลาวด์ของ Xbox และอุปกรณ์เสริมจอย Xbox ส่วน Valorant และ FiveM ไม่ได้ใช้'
        'tw.svciphelper' = 'ปิด IP Helper'; 'tw.svciphelper.d' = 'IPv6 tunnel (Teredo) ที่ปาร์ตี้แชตของ Xbox Live และบางเกมใช้เชื่อมต่อ'
        'tw.svchello' = 'ปิด Windows Hello (สแกนนิ้ว/หน้า)'; 'tw.svchello.d' = 'สแกนนิ้วและสแกนหน้าเข้า Windows จะใช้ไม่ได้ ส่วน PIN และรหัสผ่านยังใช้ได้'
        'tw.svcscanner' = 'ปิดสแกนเนอร์และกล้อง (WIA)'; 'tw.svcscanner.d' = 'สแกนเนอร์ และเว็บแคมรุ่นเก่าบางตัว เว็บแคม USB ส่วนใหญ่ไม่ต้องใช้'
        'tw.svchotspot' = 'ปิด Mobile hotspot'; 'tw.svchotspot.d' = 'การแชร์เน็ตจากคอมเครื่องนี้ให้อุปกรณ์อื่น'
        'tw.svcnotify' = 'ปิด service การแจ้งเตือน'; 'tw.svcnotify.d' = 'การแจ้งเตือนของทุกแอปและศูนย์การแจ้งเตือน บางแอปอาจทำงานแปลกๆ ถ้าเจอให้เปิดกลับ'
        'tw.svccdp' = 'ปิด Connected Devices'; 'tw.svccdp.d' = 'Phone Link, Nearby sharing และการแชร์ข้ามอุปกรณ์'
        'ac.title' = 'โหมด anti-cheat'; 'ac.sub' = 'Valorant (Vanguard) อาจต้องเปิด Memory integrity ส่วน FiveM ต้องปิด เลือกเกมที่จะเล่นต่อไป Windows จะเปลี่ยนให้หลังรีสตาร์ต'
        'ac.valorant' = 'โหมด Valorant'; 'ac.fivem' = 'โหมด FiveM'; 'ac.on' = 'Memory integrity: เปิด (โหมด Valorant)'; 'ac.off' = 'Memory integrity: ปิด (โหมด FiveM)'; 'ac.pending' = 'รีสตาร์ตเพื่อให้มีผล'
        'ac.restartask' = 'Windows จะเปลี่ยน Memory integrity ตอนเปิดเครื่อง รีสตาร์ตเลยไหม'
        'restart.bar' = 'รีสตาร์ตเพื่อให้การเปลี่ยนแปลงมีผล'; 'restart.now' = 'รีสตาร์ตเลย'; 'restart.ask' = 'รีสตาร์ตเครื่องตอนนี้เลยไหม บันทึกงานก่อนนะ'
        'toast.on' = 'เปิด: {0}'; 'toast.off' = 'ปิด: {0}'; 'toast.undo' = 'เลิกทำ'; 'tw.details' = 'ดูว่าเปลี่ยนอะไร'; 'spot.recent' = 'ล่าสุด'
        'side.narrow' = 'ย่อแถบข้าง'; 'side.wide' = 'ขยายแถบข้าง'
        'preset.title' = 'สไตล์สำเร็จรูป'; 'preset.sub' = 'วอลเปเปอร์ สีหลัก หน้าตา Akati OS Center เคอร์เซอร์ และเสียง ในคลิกเดียว'
        'preset.neon' = 'Neon'; 'preset.ocean' = 'Ocean'; 'preset.ember' = 'Ember'; 'preset.sakura' = 'Sakura'; 'preset.stealth' = 'Stealth (OLED)'
        'status.preset' = 'ใช้สไตล์ {0} แล้ว'; 'accent.wallpaper' = 'ตามวอลเปเปอร์'; 'accent.nowallcolor' = 'วอลเปเปอร์ไม่มีสีให้ดึง (ดำ ขาว หรือเทา)'
        'tw.group.looks' = 'หน้าตา Windows'
        'tw.darkmode' = 'โหมดมืด'; 'tw.darkmode.d' = 'Windows และแอปใช้สีเข้ม'
        'tw.accentbars' = 'สีหลักบนแถบหัวหน้าต่างและทาสก์บาร์'; 'tw.accentbars.d' = 'แถบหัวหน้าต่าง Start และทาสก์บาร์ใช้สีหลักจากหน้าธีม'
        'tw.transparency' = 'เอฟเฟกต์โปร่งใส'; 'tw.transparency.d' = 'Start ทาสก์บาร์ และหน้าต่างแบบโปร่งแสง ปิดไว้ช่วยลดงาน GPU เล็กน้อย'
        'tw.widget' = 'วิดเจ็ตประสิทธิภาพ'; 'tw.widget.d' = 'แถบเล็ก ๆ อยู่บนหน้าต่างอื่น แสดง CPU, RAM, GPU, อุณหภูมิ GPU และปิง ลากเพื่อย้าย คลิกขวาเพื่อปิด มีในเมนูไอคอนข้างนาฬิกาด้วย'
        'chip.doctor.ok' = 'สุขภาพเครื่อง: ปกติดี'; 'chip.doctor.bad' = 'สุขภาพเครื่อง: มี {0} เรื่องควรดู'
        'nav.health' = 'สุขภาพเครื่อง'; 'doc.title' = 'Akati Doctor'; 'doc.run' = 'ตรวจอีกครั้ง'; 'doc.checking' = 'กำลังตรวจเครื่อง...'
        'doc.allgood' = 'ทุกอย่างปกติดี'; 'doc.issues' = 'มี {0} เรื่องที่ควรดู'; 'doc.checked' = 'ตรวจเมื่อ {0}'
        'doc.failed' = 'ตรวจไม่สำเร็จ'; 'doc.fixing' = 'กำลังแก้...'
        'doc.tray.ok' = 'ไอคอนข้างนาฬิกาตั้งค่าไว้แล้ว'; 'doc.tray.bad' = 'ไอคอนข้างนาฬิกายังไม่ได้ตั้งค่า'; 'doc.fix.tray' = 'ตั้งค่า'
        'doc.menu.ok' = 'เมนูคลิกขวาบนเดสก์ท็อปใช้งานได้'; 'doc.menu.bad' = 'งานของเมนูคลิกขวาบนเดสก์ท็อปหายไป'; 'doc.fix.menu' = 'ซ่อม'
        'doc.power.ok' = 'ใช้แผนพลังงานแบบประสิทธิภาพสูงอยู่'; 'doc.power.bad' = 'กำลังใช้แผนพลังงานแบบสมดุลหรือประหยัดพลังงาน'; 'doc.fix.power' = 'ใช้ประสิทธิภาพสูงสุด'
        'doc.disk.ok' = 'ไดรฟ์ Windows ว่าง {0}%'; 'doc.disk.bad' = 'ไดรฟ์ Windows ว่างเหลือแค่ {0}%'; 'doc.fix.disk' = 'ล้างไฟล์ขยะ'
        'doc.restart.ok' = 'ไม่มีอะไรรอรีสตาร์ท'; 'doc.restart.bad' = 'Windows รอรีสตาร์ทเพื่อติดตั้งอัปเดตให้เสร็จ'; 'doc.fix.restart' = 'รีสตาร์ท'
        'doc.hvci.ok' = 'Memory integrity ทำงานตามที่ตั้งไว้'; 'doc.hvci.bad' = 'Memory integrity จะเปลี่ยนหลังรีสตาร์ท'; 'doc.fix.hvci' = 'รีสตาร์ท'
        'doc.devices.ok' = 'อุปกรณ์ทั้งหมดทำงานปกติ'; 'doc.devices.bad' = 'อุปกรณ์ {0} ตัวมีปัญหา (ไม่มีไดรเวอร์หรือไม่ทำงาน)'; 'doc.fix.devices' = 'Device Manager'
        'doc.crash.ok' = 'ไม่มีจอฟ้าใน 7 วันที่ผ่านมา'; 'doc.crash.bad' = 'จอฟ้า {0} ครั้งใน 7 วันที่ผ่านมา'; 'doc.fix.crash' = 'ดู'
        'doc.repair' = 'ซ่อมไฟล์ Windows'; 'doc.repair.d' = 'รัน DISM และ SFC ในหน้าต่างใหม่ ใช้เวลา 10-30 นาทีและต้องต่ออินเทอร์เน็ต'; 'doc.repair.button' = 'ซ่อม'
        'health.speed' = 'การเปิดเครื่องและอุณหภูมิ'; 'boot.last' = 'เปิด Windows เสร็จใน {0:N1} วินาที'
        'boot.avg' = 'ครั้งล่าสุด ค่าเฉลี่ย {0} ครั้งหลังสุด: {1:N1} วินาที'
        'boot.none' = 'Windows ยังไม่ได้บันทึกเวลาเปิดเครื่อง (log Diagnostics-Performance ปิดอยู่หรือยังว่าง)'
        'boot.off' = 'Windows นี้ไม่ได้บันทึกเวลาเปิดเครื่อง (log Diagnostics-Performance ถูกปิดไว้)'
        'boot.enable' = 'เปิดการบันทึกเวลาเปิดเครื่อง'; 'boot.next' = 'เปิดการบันทึกแล้ว เวลาจะแสดงที่นี่หลังรีสตาร์ทครั้งถัดไป'; 'boot.failed' = 'Windows เปิด log ไม่สำเร็จ'
        'temp.now' = 'อุณหภูมิตอนนี้: {0}'; 'temp.none' = 'เครื่องนี้ไม่ส่งค่าอุณหภูมิให้ Windows ใช้ HWiNFO เพื่อดูเซนเซอร์ทั้งหมด'
        'chip.temp.sys' = 'ระบบ {0}°C'; 'chip.temp.gpu' = 'GPU {0}°C'
        'crash.title' = 'การแครชใน 30 วันที่ผ่านมา'; 'crash.none' = 'ไม่มีการแครช เยี่ยมเลย'; 'crash.bsod' = 'จอฟ้า {0}'
        'crash.power' = 'เครื่องดับโดยไม่ได้ปิดตามปกติ'; 'crash.app' = '{0} หยุดทำงาน'; 'crash.folder' = 'โฟลเดอร์ crash dump'
        'wu.title' = 'Windows Update'; 'wu.sub' = 'หยุดอัปเดตชั่วคราวก่อนแข่งหรือก่อนเล่นยาว ๆ อัปเดตจะกลับมาเองเมื่อครบกำหนด'
        'wu.on' = 'อัปเดตเปิดอยู่'; 'wu.paused' = 'หยุดอัปเดตถึง {0}'; 'wu.pause7' = 'หยุด 1 สัปดาห์'; 'wu.pause35' = 'หยุด 5 สัปดาห์'
        'wu.resume' = 'อัปเดตต่อ'; 'wu.open' = 'เปิด Windows Update'
        'history.title' = 'ประวัติการเปลี่ยนแปลง'; 'history.none' = 'สวิตช์ที่เปลี่ยนในหน้าปรับแต่งจะแสดงที่นี่ พร้อมปุ่มเลิกทำ'; 'history.clear' = 'ล้าง'
        'history.on' = 'เปิด'; 'history.off' = 'ปิด'
        'backup.title' = 'สำรองข้อมูล'; 'backup.sub' = 'บันทึกการตั้งค่า Akati OS Center, เกมของฉันพร้อมโปรไฟล์ และสวิตช์ทั้งหมดลงไฟล์ แล้วกู้คืนหลังลงเครื่องใหม่'
        'backup.save' = 'บันทึกไฟล์สำรอง'; 'backup.load' = 'กู้คืน'; 'backup.saved' = 'บันทึกไฟล์สำรองแล้ว: {0}'
        'backup.ask' = 'กู้คืนการตั้งค่าจากไฟล์นี้? สวิตช์ที่ต่างกันจะถูกเปลี่ยนทันที'
        'backup.restored' = 'กู้คืนแล้ว เปลี่ยนสวิตช์ {0} ตัว การตั้งค่าบางอย่างจะแสดงเมื่อเปิด Akati OS Center ใหม่'; 'backup.bad' = 'ไฟล์นี้ไม่ใช่ไฟล์สำรองของ Akati OS'
        'tw.mouseaccel' = 'Mouse acceleration'; 'tw.mouseaccel.d' = 'Enhance pointer precision ของ Windows ปิดไว้: เมาส์เลื่อนระยะเท่าเดิมไม่ว่าจะขยับเร็วแค่ไหน เหมาะกับการเล็ง'
        'tw.ducking' = 'ลดเสียงอื่นขณะคุยสาย'; 'tw.ducking.d' = 'Windows ลดเสียงเกมลง 80% เมื่อมีการโทร (Discord อาจทำให้เกิด) ปิดไว้เสียงเกมจะดังเท่าเดิม'
        'tw.keydelay' = 'หน่วงการกดค้างสั้นที่สุด'; 'tw.keydelay.d' = 'กดปุ่มค้างแล้วตัวอักษรซ้ำเร็วขึ้น มีผลหลังล็อกอินใหม่'
        'games.boost' = 'บูสต์'; 'games.boost.tip' = 'กดเล่นแล้วเริ่มบูสต์เกมก่อน'; 'games.core0' = 'ไม่ใช้ CPU 0'
        'games.core0.tip' = 'ให้เกมใช้ทุกคอร์ยกเว้น CPU 0 ที่ Windows ใช้จัดการ interrupt เป็นหลัก ไอคอนข้างนาฬิกาจะตั้งให้ตอนเกมเปิด'
        'games.hvci.any' = 'Memory integrity: ไม่สนใจ'; 'games.hvci.on' = 'ต้องเปิด Memory integrity'; 'games.hvci.off' = 'ต้องปิด Memory integrity'
        'games.hvci.tip' = 'Valorant อาจต้องเปิด FiveM ต้องปิด กดเล่นแล้วจะถามให้สลับให้'; 'games.play' = 'เล่น'; 'games.on' = 'เปิด'; 'games.off' = 'ปิด'
        'games.hvciask' = '{0} ต้อง{1} Memory integrity สลับตอนนี้เลยไหม Windows จะเปลี่ยนให้หลังรีสตาร์ต (กด No เพื่อเปิดเกมตามเดิม)'; 'status.gamestarted' = 'เปิด {0} แล้ว'
        'fivem.title' = 'FiveM'; 'fivem.sub' = 'ล้างแคชเมื่อเข้าเซิร์ฟช้าหรือเท็กซ์เจอร์เพี้ยน และวัดเวลาเชื่อมต่อไปเซิร์ฟเวอร์ของคุณ'
        'fivem.found' = 'พบ FiveM: {0}'; 'fivem.none' = 'ยังไม่ได้ลง FiveM ในบัญชีนี้'; 'fivem.clear' = 'ล้างแคช'; 'fivem.open' = 'เปิดโฟลเดอร์'; 'fivem.add' = 'เพิ่มในเกมของฉัน'
        'fivem.server' = 'IP:port ของเซิร์ฟเวอร์ เช่น 1.2.3.4:30120'; 'fivem.ping' = 'ทดสอบ'; 'fivem.running' = 'ปิด FiveM ก่อน'; 'fivem.cleared' = 'ล้างแคช FiveM แล้ว: {0}'
        'fivem.result' = 'เวลาเชื่อมต่อไป {0}: {1} ms'; 'fivem.fail' = 'เชื่อมต่อ {0} ไม่ได้'; 'fivem.added' = 'เพิ่ม FiveM ในเกมของฉันแล้ว'
        'boost.sound' = 'มีเสียงและเอฟเฟกต์ตอนเริ่มบูสต์เกม'
        'tw.hotkeys' = 'ปุ่มลัด'; 'tw.hotkeys.d' = 'Ctrl+Alt+B เปิด/ปิดบูสต์เกม และ Ctrl+Alt+R ล้าง RAM ใช้ได้แม้อยู่ในเกม ต้องเปิดไอคอนข้างนาฬิกาไว้'
        'tw.vbs' = 'Core isolation (VBS และ Memory integrity)'; 'tw.vbs.d' = 'ปิดแล้วเกมเร็วขึ้นได้ถึงประมาณ 10% แต่การป้องกันมัลแวร์บางส่วนหายไป anti-cheat บางตัว (Valorant, FACEIT) อาจต้องเปิดไว้ (ค่าเดียวกับสคริปต์ VBS ในหมวดระบบด้านล่าง)'
        'tw.desktopmenu' = 'เมนู Akati OS ตอนคลิกขวาที่ Desktop'; 'tw.desktopmenu.d' = 'คลิกขวาที่ Desktop > Akati OS: ล้าง RAM, แอปของฉัน, บูสต์เกม, ล้างไฟล์ขยะ, ทดสอบปิง, ล้าง DNS, รีสตาร์ต Explorer, รีสตาร์ตเข้า BIOS'
        'tw.startdelay' = 'หน่วงเวลาแอปที่เปิดตอนล็อกอิน'; 'tw.startdelay.d' = 'ปิด: แอปที่เปิดตอนล็อกอินจะเปิดทันที ไม่ต้องรอหลายวินาที'
        'chip.hz' = 'จอ {0} Hz'; 'chip.hzlow' = 'จอ {0} Hz · ทำได้ {1} Hz'
        'games.title' = 'เกมของฉัน'; 'games.add' = 'เพิ่มเกม'; 'games.empty' = 'ยังไม่ได้เพิ่มเกม เลือกไฟล์ .exe ของเกม'
        'games.sub' = 'ความสำคัญสูง: เกมได้ CPU ก่อนแอปอื่น การ์ดจอแยก: โน้ตบุ๊กที่มีชิปกราฟิกสองตัวจะใช้ตัวแรง ข้าม Defender: Defender ไม่สแกนโฟลเดอร์เกม (โหลดเร็วขึ้น แต่ป้องกันน้อยลง) ลบเกมออกแล้วทุกอย่างกลับเหมือนเดิม'
        'games.cpu' = 'ความสำคัญสูง'; 'games.gpu' = 'การ์ดจอแยก'; 'games.defender' = 'ข้าม Defender'; 'games.remove' = 'ลบ'; 'games.nodefender' = 'Defender ปิดอยู่หรือใช้ไม่ได้'
        'games.pick' = 'เลือกเกม (.exe)'; 'status.gameadded' = 'เพิ่ม {0} แล้ว'; 'status.gameremoved' = 'ลบ {0} แล้ว การตั้งค่ากลับเป็นเหมือนเดิม'
        'look.title' = 'หน้าตา Akati OS Center'; 'look.sub' = 'อัตโนมัติจะตามโหมดแอปของ Windows (Settings > Personalization > Colors)'; 'look.auto' = 'อัตโนมัติ'; 'look.dark' = 'มืด'; 'look.light' = 'สว่าง'
        'spot.search' = 'ค้นหา'; 'spot.hint' = 'ค้นหาหน้า การตั้งค่า แอป และคำสั่ง'; 'spot.none' = 'ไม่พบ'
        'spot.page' = 'หน้า'; 'spot.setting' = 'การตั้งค่า'; 'spot.app' = 'แอป'; 'spot.action' = 'คำสั่ง'; 'spot.game' = 'เกม'; 'spot.atlas' = 'ค้นหา "{0}" ในการตั้งค่า Windows'
        'act.freeram' = 'ล้าง RAM'; 'act.flushdns' = 'ล้าง DNS cache'; 'act.explorer' = 'รีสตาร์ต Explorer'; 'act.boost' = 'เริ่มหรือหยุดบูสต์เกม'
        'act.update' = 'ตรวจอัปเดต Akati OS'; 'act.lang' = 'เปลี่ยนภาษา (English / ภาษาไทย)'; 'act.ping' = 'ทดสอบปิง'; 'act.report' = 'สร้างรายงานปัญหา'
        'status.freed' = 'คืน RAM ได้ {0}'; 'status.dnsflushed' = 'ล้าง DNS cache แล้ว'
        'new.title' = 'มีอะไรใหม่ใน Akati OS {0}'; 'new.done' = 'ไปต่อ'
        'new.1' = 'แดชบอร์ด: กราฟสด แอปที่ใช้ทรัพยากรมากสุด ความเร็วเน็ตและปิง ไดรฟ์ และอัตรารีเฟรชจอ'
        'new.2' = 'แอปเกมหน้าตาแบบ App Store เพิ่ม Riot Client, GOG GALAXY, Rockstar Games Launcher และ MSI Afterburner'
        'new.3' = 'ปรับแต่ง: หมวดใหม่ อินพุตและ latency, เครือข่าย (DNS), หน้าจอ (อัตรารีเฟรช) และหน่วยความจำ พร้อมปุ่มคืนค่าเริ่มต้นของ Windows'
        'new.4' = 'บูสต์เกมคืน RAM ได้ มีเกมของฉัน (ความสำคัญ CPU, การ์ดจอ) และเริ่มเองได้เมื่อเปิดเกม'
        'new.5' = 'คลิกขวาที่ Desktop หรือไอคอน Akati OS ข้างนาฬิกา: ล้าง RAM แอปของฉัน บูสต์เกม และอื่น ๆ'
        'new.6' = 'ค้นหาทุกอย่างด้วย Ctrl+K และหน้าตาแบบสว่าง (ธีม > หน้าตา Akati OS Center)'
        'boost.auto' = 'เริ่มเองเมื่อเปิดเกมในเกมของฉัน และหยุดเมื่อปิดเกม'
        'tweaks.reset' = 'คืนค่าเริ่มต้นของ Windows'; 'tweaks.resetask' = 'คืนค่า Game Mode, timer resolution, ปุ่มลัด Sticky Keys, Nagle, การ์ดแลน, MPO, memory compression, การหน่วงแอปตอนล็อกอิน และ DNS เป็นค่าเริ่มต้นของ Windows ใช่ไหม'
        'status.reset' = 'คืนค่าเริ่มต้นของ Windows แล้ว · รีสตาร์ตเพื่อให้ครบ'
        'tw.tray' = 'ไอคอน Akati OS ข้างนาฬิกา'; 'tw.tray.d' = 'ชี้แล้วเห็น CPU และ RAM มีเมนูแอปและเครื่องมือ และใช้กับบูสต์เกมอัตโนมัติ เปิดเองตอนล็อกอิน'
        'theme.dark' = 'Akati OS Dark'; 'theme.light' = 'Akati OS Light'; 'theme.slideshow' = 'Akati OS Slideshow'
        'theme.slideshow.d' = 'เปลี่ยน wallpaper ทุก 30 นาที'
        'nav.boost' = 'บูสต์เกม'
        'cancel' = 'ยกเลิก'; 'cancelling' = 'กำลังยกเลิก...'; 'queued' = 'รอคิว'; 'preparing' = 'กำลังเริ่ม...'
        'update' = 'อัปเดต'; 'updating' = 'กำลังอัปเดต...'; 'updateavailable' = 'มีอัปเดต'; 'selfupdate' = 'อัปเดตตัวเอง'
        'apps.check' = 'ตรวจอัปเดต'; 'apps.updateall' = 'อัปเดตทั้งหมด'; 'apps.updatecount' = 'อัปเดตทั้งหมด ({0})'
        'apps.hint' = 'กดติดตั้งหลายแอปได้ ระบบจะติดตั้งให้ทีละตัว'; 'apps.starter' = 'ติดตั้ง Steam และ Discord'
        'apps.cat.installed' = 'ติดตั้งแล้ว'; 'src.winget' = 'WinGet'; 'src.official' = 'เว็บทางการ'
        'apps.cat.launchers' = 'ตัวเปิดเกม'; 'apps.cat.social' = 'แชทและสตรีม'; 'apps.cat.tools' = 'เครื่องมือ'
        'get' = 'ติดตั้ง'; 'open' = 'เปิด'; 'more' = 'เพิ่มเติม'; 'openfolder' = 'เปิดโฟลเดอร์'; 'uninstall' = 'ถอนการติดตั้ง'
        'uninstall.confirm' = 'ถอนการติดตั้ง {0} ใช่ไหม ตัวถอนการติดตั้งของแอปจะเปิดขึ้นมา'; 'uninstalling' = 'กำลังถอนการติดตั้ง ทำต่อในหน้าต่างของแอป...'
        'status.opening' = 'กำลังเปิด {0}'; 'status.uninstalled' = 'ถอนการติดตั้ง {0} แล้ว'; 'status.nouninstaller' = 'ไม่พบตัวถอนการติดตั้งของ {0} กำลังเปิด Apps and features'
        'app.desc.Steam' = 'ร้านเกม PC ที่ใหญ่ที่สุด และคลังเกม Steam ของคุณ'; 'app.desc.Epic' = 'Fortnite, เกมเฉพาะ Epic และเกมฟรีทุกสัปดาห์'
        'app.desc.EA' = 'EA SPORTS FC, Apex Legends, Battlefield และ EA Play'; 'app.desc.Ubisoft' = "Assassin's Creed, Rainbow Six Siege และ Ubisoft+"
        'app.desc.BattleNet' = 'Overwatch 2, Diablo, World of Warcraft และ Call of Duty'; 'app.desc.Riot' = 'ติดตั้ง VALORANT (เอเชียแปซิฟิก) ส่วน League of Legends และ TFT เพิ่มได้ใน Riot Client'
        'app.desc.GOG' = 'เกมไม่มี DRM และรวมคลังเกมจากทุกร้านไว้ที่เดียว'; 'app.desc.Rockstar' = 'GTA V, Red Dead Redemption 2 และเกมของ Rockstar'
        'app.desc.Discord' = 'แชทเสียง วิดีโอ และข้อความกับเพื่อน'; 'app.desc.OBS' = 'อัดและสตรีมเกม'
        'app.desc.Afterburner' = 'ดู FPS อุณหภูมิ และการใช้ GPU บนจอระหว่างเล่น และปรับแต่งการ์ดจอ'
        'gpu.driver' = '{0}: ไดรเวอร์ {1} วันที่ {2}'; 'gpu.old' = 'เก่ากว่า 6 เดือน ลองดูว่ามีไดรเวอร์ใหม่กว่านี้ไหม'
        'stage.winget' = 'กำลังติดตั้งด้วย WinGet...'; 'stage.download' = 'กำลังดาวน์โหลด'; 'stage.install' = 'กำลังติดตั้ง...'
        'stage.user' = 'กำลังติดตั้งให้บัญชีของคุณ...'; 'stage.finish' = 'กำลังจบการติดตั้ง...'
        'stage.window' = 'กด Install ในหน้าต่างของแอปเพื่อติดตั้งต่อ...'
        'status.cancelled' = '{0}: ยกเลิกแล้ว'; 'status.updating' = 'กำลังอัปเดต {0}...'; 'status.updated' = 'อัปเดต {0} แล้ว'
        'status.updatefailed' = 'อัปเดต {0} ไม่สำเร็จ'; 'status.checkingapps' = 'กำลังตรวจอัปเดตแอปจาก WinGet...'
        'status.updatesfound' = 'มีอัปเดต {0} รายการ'; 'status.noupdates' = 'แอปทั้งหมดเป็นเวอร์ชันล่าสุด'
        'status.nowinget' = 'ไม่มี WinGet ในเครื่อง'
        'gpu.detected' = 'ตรวจพบในเครื่อง: {0}'; 'gpu.none' = 'ไม่พบการ์ดจอ NVIDIA, AMD หรือ Intel (อาจเป็น VM)'
        'boost.title' = 'บูสต์เกม'
        'boost.sub' = 'กดครั้งเดียวก่อนเล่นเกม กดหยุดแล้วทุกอย่างจะกลับเป็นเหมือนเดิม แม้รีสตาร์ตเครื่องไปแล้ว'
        'boost.mode' = 'โหมดเกม'; 'boost.off' = 'ปิดอยู่'; 'boost.on' = 'เปิดตั้งแต่ {0}'; 'boost.start' = 'เริ่ม'; 'boost.stop' = 'หยุด'
        'boost.power' = 'เปลี่ยนเป็น power plan ประสิทธิภาพสูงสุด'
        'boost.apps' = 'ปิดแอปเบื้องหลัง'; 'boost.noapps' = 'ตอนนี้ไม่มีที่เปิดอยู่'
        'boost.notify' = 'ปิดการแจ้งเตือน'
        'boost.memory' = 'คืน standby memory (ไฟล์ที่ Windows เก็บไว้ใน RAM ช่วยเครื่อง RAM น้อย)'
        'status.booston' = 'เปิดบูสต์เกมแล้ว ขอให้สนุก!'; 'status.boostoff' = 'ปิดบูสต์เกมแล้ว การตั้งค่ากลับเป็นเหมือนเดิม'
        'ping.title' = 'ปิงไปเซิร์ฟเวอร์เกม'
        'ping.sub' = 'เวลาเชื่อมต่อไปศูนย์ข้อมูลคลาวด์ที่เกมออนไลน์หลายเกมใช้วางเซิร์ฟเวอร์เอเชีย ยิ่งต่ำยิ่งดี ต่ำกว่า 60 ms ถือว่าดีมาก'
        'ping.start' = 'เริ่มทดสอบ'; 'ping.stop' = 'หยุด'; 'ping.timeout' = 'ไม่ตอบ'
        'ping.bkk' = 'ไทย (กรุงเทพฯ)'; 'ping.sin' = 'สิงคโปร์'; 'ping.hkg' = 'ฮ่องกง'; 'ping.tyo' = 'ญี่ปุ่น (โตเกียว)'
        'startup.title' = 'แอปที่เปิดตอนบูต'
        'startup.sub' = 'แอปที่เปิดเองตอนเข้าสู่ระบบ ยิ่งน้อยเครื่องยิ่งเปิดเร็ว และเหลือ RAM ให้เกมมากขึ้น'
        'startup.empty' = 'ไม่มีแอปที่เปิดตอนบูต'
        'status.startupon' = '{0} จะเปิดพร้อม Windows'; 'status.startupoff' = '{0} จะไม่เปิดพร้อม Windows แล้ว'
        'system.default' = 'ค่าเริ่มต้น'
        'restore.title' = 'สร้างจุดคืนค่าก่อนเปลี่ยน'; 'restore.open' = 'System Restore'
        'restore.sub' = 'สร้างครั้งเดียวก่อนการเปลี่ยนแปลงแรกในหน้านี้ ต้องเปิด System Restore ไว้'
        'status.restoring' = 'กำลังสร้างจุดคืนค่า...'
        'status.restore.made' = 'สร้างจุดคืนค่าแล้ว'
        'status.restore.recent' = 'ไม่ได้สร้างจุดคืนค่าใหม่ เพราะ Windows สร้างไว้แล้วในช่วง 24 ชั่วโมง'
        'status.restore.off' = 'สร้างจุดคืนค่าไม่ได้ เพราะ System Restore ปิดอยู่ เปิดได้ที่ปุ่ม System Restore (Configure > Turn on system protection)'
        'status.boostpartial' = 'เปิดบูสต์เกมแล้ว แต่ขั้นเหล่านี้ไม่สำเร็จ: {0}'
        'status.sound.play' = 'กำลังเล่น: {0}'
        'report.title' = 'แจ้งปัญหา'
        'report.sub' = 'บันทึกไฟล์ .zip ไฟล์เดียวไว้บนเดสก์ท็อป มี log ของ Akati OS และข้อมูลเครื่อง ไม่มีไฟล์ส่วนตัว และลบชื่อผู้ใช้กับชื่อเครื่องออกแล้ว แนบไฟล์นี้ใน GitHub issue'
        'report.button' = 'สร้างรายงานปัญหา'; 'report.issues' = 'GitHub issues'
        'status.report' = 'กำลังสร้างรายงานปัญหา...'; 'status.reportdone' = 'บันทึกไว้บนเดสก์ท็อปแล้ว: {0}'; 'status.reportfailed' = 'สร้างรายงานไม่สำเร็จ'
        'accent.title' = 'สีหลัก'
        'accent.sub' = 'ใช้กับ Akati OS Center, สีเน้นของ Windows (ไฮไลต์ ปุ่ม และลิงก์ ส่วน Start และ taskbar จะเปลี่ยนเมื่อเปิด "แสดงสีเน้น" ใน Settings) และสีของ Terminal แบบ Akati OS'
        'accent.purple' = 'ม่วง'; 'accent.blue' = 'น้ำเงิน'; 'accent.cyan' = 'ฟ้า'; 'accent.green' = 'เขียว'
        'accent.pink' = 'ชมพู'; 'accent.red' = 'แดง'; 'accent.orange' = 'ส้ม'
        'status.accent' = 'สีหลัก: {0} บางส่วนของ Windows จะเปลี่ยนหลังออกจากระบบแล้วเข้าใหม่'
        'wall.title' = 'วอลเปเปอร์'; 'wall.sub' = 'คลิกรูปเพื่อใช้เป็นพื้นหลังเดสก์ท็อป'
        'status.wallpaper' = 'เปลี่ยนวอลเปเปอร์เป็น {0} แล้ว'
        'style.title' = 'เคอร์เซอร์และเสียง'
        'style.sub' = 'เคอร์เซอร์และเสียงระบบของ Akati OS เปลี่ยนกลับเป็นของ Windows ได้ทุกเมื่อ'
        'style.cursor' = 'เคอร์เซอร์'; 'style.sounds' = 'เสียง'; 'style.akati' = 'Akati OS'; 'style.windows' = 'Windows'
        'style.nosound' = 'ไม่มีเสียง'; 'style.preview' = 'ลองฟัง'
        'status.cursor.akati' = 'ใช้เคอร์เซอร์ Akati OS แล้ว'; 'status.cursor.windows' = 'กลับไปใช้เคอร์เซอร์ Windows แล้ว'
        'status.sound.akati' = 'ใช้เสียง Akati OS แล้ว'; 'status.sound.windows' = 'ใช้เสียง Windows แล้ว'; 'status.sound.none' = 'ปิดเสียงระบบแล้ว'
        'welcome.title' = 'ยินดีต้อนรับสู่ Akati OS'; 'welcome.sub' = '3 ขั้นสั้น ๆ เปลี่ยนทีหลังได้ทุกอย่าง'
        'welcome.lang' = 'ภาษา'; 'welcome.apps' = 'ติดตั้งแอปเกม'; 'welcome.apps.d' = 'Steam, Discord, Epic และอื่น ๆ'
        'welcome.look' = 'เลือกธีมและสีหลัก'; 'welcome.look.d' = 'ธีมมืด สว่าง สไลด์โชว์ และ 7 สี'
        'welcome.open' = 'เปิด'; 'welcome.done' = 'เริ่มใช้งาน'
        'welcome.keys' = 'ทิป: Ctrl+1 ถึง Ctrl+8 สลับหน้า, Ctrl+F ค้นหาการตั้งค่า'
        'lang' = 'English'
    }
}
